### ISSUE TITLE
Prezentacja: dekompozycja na trendy i sezony, autokorelacje

### ISSUE THREAD

**Issue by igorsieradzki** [gmum/TimeSeriesNotes#3]
* autokorelacja: funkcje ACF, PACF
* sezonowość, a cykliczność

**Comment by Lamiane** [comment]
ten tutorial znalazłeś czy inny? https://www.analyticsvidhya.com/blog/2016/02/time-series-forecasting-codes-python/. To jest chyba 'to samo", ale z ładniejszymi tłumaczeniami: http://www.seanabu.com/2016/03/22/time-series-seasonal-ARIMA-model-in-python/

**Comment by igorsieradzki** [comment]
Oby dwa widziałem :)

Ten drugi ma inne dane, ale idea jest taka sama.
