### ISSUE TITLE
Prezentacja: model selection, model evaluation dla TS

### ISSUE THREAD

**Issue by igorsieradzki** [gmum/TimeSeriesNotes#4]
* różne rodzaje problemów: reliability, forecasting, itd
* różne funckję kosztu
* CV dla TS

**Comment by Lamiane** [comment]
książka, której nie da się ukraść, a w której jest rozdział dokładnie o tym, co chcemy: Computer Intensive Statistical Methods: Validation,  Model Selection, and Bootstrap,  J. S. Urban. Hjorth
książka, gdzie są jakieś rzeczy bardziej dla @igorsieradzki : https://www.otexts.org/fpp/

**Comment by Lamiane** [comment]
W tej drugiej publikacji mówią o Theil's U. Podobno dobra miara do porównywania modeli dla szeregów czasowych. Warto zbadać.

**Comment by Lamiane** [comment]
@lesniak43 
- walidacja krzyżowa dla time series
- bootstrap dla time series
- naklepać metryki i wygenerować dla przykładowego zbioru każdy error zgodnie ze sztuką
